// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyTrungTamTinHoc_NgoaiNgu.Data;

#nullable disable

namespace QuanLyTrungTamTinHoc_NgoaiNgu.Migrations
{
    [DbContext(typeof(QuanLyTrungTamContext))]
    [Migration("20260302131256_KhoiTaoCSDL")]
    partial class KhoiTaoCSDL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.CaHoc", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("time");

                    b.HasKey("ID");

                    b.ToTable("CaHoc");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.GiangVien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ChuyenMon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaiKhoanID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TaiKhoanID");

                    b.ToTable("GiangVien");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.HocPhi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("HocVienID")
                        .HasColumnType("int");

                    b.Property<int>("LopHocID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDong")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoTienDaDong")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("HocVienID");

                    b.HasIndex("LopHocID");

                    b.ToTable("HocPhi");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.HocVien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaiKhoanID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TaiKhoanID");

                    b.ToTable("HocVien");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.KetQua", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<float>("DiemSo")
                        .HasColumnType("real");

                    b.Property<int>("HocVienID")
                        .HasColumnType("int");

                    b.Property<int>("LanThi")
                        .HasColumnType("int");

                    b.Property<int>("LoaiDiemID")
                        .HasColumnType("int");

                    b.Property<int>("LopHocID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("HocVienID");

                    b.HasIndex("LoaiDiemID");

                    b.HasIndex("LopHocID");

                    b.ToTable("KetQua");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.KhoaHoc", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("HocPhi")
                        .HasColumnType("int");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThoiLuong")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("KhoaHoc");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.LichHoc", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BuoiSo")
                        .HasColumnType("int");

                    b.Property<int>("CaHocID")
                        .HasColumnType("int");

                    b.Property<int>("GiangVienID")
                        .HasColumnType("int");

                    b.Property<int>("LopHocID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayHoc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhongHocID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CaHocID");

                    b.HasIndex("GiangVienID", "CaHocID", "NgayHoc")
                        .IsUnique();

                    b.HasIndex("LopHocID", "CaHocID", "NgayHoc")
                        .IsUnique();

                    b.HasIndex("PhongHocID", "CaHocID", "NgayHoc")
                        .IsUnique();

                    b.ToTable("LichHoc");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.LoaiDiem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<float>("HeSo")
                        .HasColumnType("real");

                    b.Property<string>("TenLoaiDiem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("LoaiDiem");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.LopHoc", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("KhoaHocID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenLopHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("KhoaHocID");

                    b.ToTable("LopHoc");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.NhanVien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaiKhoanID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TaiKhoanID");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.PhongHoc", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("SucChua")
                        .HasColumnType("int");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("PhongHoc");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.TaiKhoan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuyenHan")
                        .HasColumnType("int");

                    b.Property<string>("TenDN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("TenDN")
                        .IsUnique();

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.GiangVien", b =>
                {
                    b.HasOne("QuanLyTrungTamTinHoc_NgoaiNgu.Data.TaiKhoan", "TaiKhoan")
                        .WithMany("GiangVien")
                        .HasForeignKey("TaiKhoanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.HocPhi", b =>
                {
                    b.HasOne("QuanLyTrungTamTinHoc_NgoaiNgu.Data.HocVien", "HocVien")
                        .WithMany("HocPhi")
                        .HasForeignKey("HocVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTrungTamTinHoc_NgoaiNgu.Data.LopHoc", "LopHoc")
                        .WithMany("HocPhi")
                        .HasForeignKey("LopHocID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocVien");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.HocVien", b =>
                {
                    b.HasOne("QuanLyTrungTamTinHoc_NgoaiNgu.Data.TaiKhoan", "TaiKhoan")
                        .WithMany("HocVien")
                        .HasForeignKey("TaiKhoanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.KetQua", b =>
                {
                    b.HasOne("QuanLyTrungTamTinHoc_NgoaiNgu.Data.HocVien", "HocVien")
                        .WithMany("KetQua")
                        .HasForeignKey("HocVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTrungTamTinHoc_NgoaiNgu.Data.LoaiDiem", "LoaiDiem")
                        .WithMany("KetQua")
                        .HasForeignKey("LoaiDiemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTrungTamTinHoc_NgoaiNgu.Data.LopHoc", "LopHoc")
                        .WithMany("KetQua")
                        .HasForeignKey("LopHocID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocVien");

                    b.Navigation("LoaiDiem");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.LichHoc", b =>
                {
                    b.HasOne("QuanLyTrungTamTinHoc_NgoaiNgu.Data.CaHoc", "CaHoc")
                        .WithMany("LichHoc")
                        .HasForeignKey("CaHocID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTrungTamTinHoc_NgoaiNgu.Data.GiangVien", "GiangVien")
                        .WithMany("LichHoc")
                        .HasForeignKey("GiangVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTrungTamTinHoc_NgoaiNgu.Data.LopHoc", "LopHoc")
                        .WithMany("LichHoc")
                        .HasForeignKey("LopHocID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTrungTamTinHoc_NgoaiNgu.Data.PhongHoc", "PhongHoc")
                        .WithMany("LichHoc")
                        .HasForeignKey("PhongHocID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaHoc");

                    b.Navigation("GiangVien");

                    b.Navigation("LopHoc");

                    b.Navigation("PhongHoc");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.LopHoc", b =>
                {
                    b.HasOne("QuanLyTrungTamTinHoc_NgoaiNgu.Data.KhoaHoc", "KhoaHoc")
                        .WithMany("LopHoc")
                        .HasForeignKey("KhoaHocID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.NhanVien", b =>
                {
                    b.HasOne("QuanLyTrungTamTinHoc_NgoaiNgu.Data.TaiKhoan", "TaiKhoan")
                        .WithMany("NhanVien")
                        .HasForeignKey("TaiKhoanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.CaHoc", b =>
                {
                    b.Navigation("LichHoc");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.GiangVien", b =>
                {
                    b.Navigation("LichHoc");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.HocVien", b =>
                {
                    b.Navigation("HocPhi");

                    b.Navigation("KetQua");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.KhoaHoc", b =>
                {
                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.LoaiDiem", b =>
                {
                    b.Navigation("KetQua");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.LopHoc", b =>
                {
                    b.Navigation("HocPhi");

                    b.Navigation("KetQua");

                    b.Navigation("LichHoc");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.PhongHoc", b =>
                {
                    b.Navigation("LichHoc");
                });

            modelBuilder.Entity("QuanLyTrungTamTinHoc_NgoaiNgu.Data.TaiKhoan", b =>
                {
                    b.Navigation("GiangVien");

                    b.Navigation("HocVien");

                    b.Navigation("NhanVien");
                });
#pragma warning restore 612, 618
        }
    }
}
